# Generated by Django 4.1 on 2023-05-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='responsible_group.responsibleperson')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.responsibleperson')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_responsible_person', to='responsible_group.responsibleperson')),
                ('last', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_responsible_person', to='responsible_group.responsibleperson')),
            ],
        ),
    ]
