# Generated by Django 4.1 on 2023-06-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_group', '0002_remove_responsibleperson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibleperson',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='responsible_group.responsibleperson'),
        ),
    ]
