# Generated by Django 4.2.3 on 2023-07-31 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_group', '0003_alter_responsibleperson_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('responsibleperson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='responsible_group.responsibleperson')),
                ('fields', models.JSONField(blank=True, null=True)),
            ],
            bases=('responsible_group.responsibleperson',),
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='type',
            field=models.CharField(choices=[('fi', 'filler'), ('co', 'confirmative')], default='co', max_length=25),
        ),
        migrations.AlterField(
            model_name='responsiblegroup',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_responsible_person', to='responsible_group.responsibleperson'),
        ),
        migrations.AlterField(
            model_name='responsiblegroup',
            name='last',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_responsible_person', to='responsible_group.responsibleperson'),
        ),
    ]
