# Generated by Django 4.2.3 on 2023-07-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_group', '0004_filler_responsibleperson_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibleperson',
            name='group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='for_option', to='responsible_group.responsiblegroup'),
            preserve_default=False,
        ),
    ]
