# Generated by Django 4.1 on 2023-06-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_list_company_remove_listitem_list_and_more'),
        ('value_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='list',
            field=models.ManyToManyField(to='value_list.list'),
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
