# Generated by Django 4.1 on 2023-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_list_delete_list_delete_listitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='list',
        ),
        migrations.AlterField(
            model_name='page',
            name='inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
