# Generated by Django 4.2.1 on 2023-06-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_html_remove_page_html_remove_page_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='html',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page.html'),
        ),
    ]
