# Generated by Django 4.1 on 2023-06-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_page_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='html',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
