# Generated by Django 4.1 on 2023-06-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
        ('page', '0007_html_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.html'),
        ),
        migrations.DeleteModel(
            name='Html',
        ),
    ]
