# Generated by Django 4.2.3 on 2023-07-30 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_htmlinputs_required_fields_alter_htmlinputs_inputs'),
        ('page', '0009_remove_page_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='inputs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interface.htmlinputs'),
        ),
    ]
