# Generated by Django 4.2.3 on 2023-07-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_page_inputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='responsible_group',
        ),
    ]
