# Generated by Django 4.1 on 2023-06-22 18:21

from django.db import migrations, models
import interface.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tags', interface.models.TagField()),
                ('inputs', interface.models.ManyTagField(blank=True, null=True)),
            ],
        ),
    ]
