# Generated by Django 4.2.3 on 2023-07-30 04:38

from django.db import migrations, models
import django.db.models.deletion
import interface.models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='html',
            name='inputs',
        ),
        migrations.CreateModel(
            name='HtmlInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', interface.models.ManyTagField(blank=True, null=True)),
                ('html', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.html')),
            ],
        ),
    ]
