# Generated by Django 4.1 on 2023-06-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userwithinfo_tel_num'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='user.user'),
            preserve_default=False,
        ),
    ]
