# Generated by Django 4.2.1 on 2023-05-27 08:32

from django.db import migrations, models
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userwithinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userwithinfo',
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userwithinfo',
            name='tel_num',
            field=models.IntegerField(max_length=7),
        ),
    ]
