# Generated by Django 4.2.1 on 2023-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userwithinfo_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithinfo',
            name='tel_num',
            field=models.BigIntegerField(),
        ),
    ]
