# Generated by Django 4.1 on 2023-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userwithinfo_tel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithinfo',
            name='tel_num',
            field=models.BigIntegerField(),
        ),
    ]
